"""make_ui_css.py <captured app.css> <out ui.css>

Builds the sting's ui.css from GoNai's own compiled CSS, as the local dev server served it
(tools/capture.mjs saves it as app.css). Nothing is restyled here:

  1. next/font faces for IBM Plex Sans Thai (400-700) and IBM Plex Mono (400-700), trimmed to the
     subsets the plan and share screens use (latin, latin-ext, thai for the baht sign), plus the
     two metric-matched fallback faces; URLs point at ./fonts/ (the same woff2 files the app serves).
  2. the two next/font variable classes (--font-plex-thai, --font-mono).
  3. app/globals.css as compiled by Tailwind v4 (theme tokens, preflight, utilities, gn-/o- classes),
     verbatim.

The Next.js dev overlay's own styles (Geist) are dropped."""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
css = open(src, encoding="utf-8").read().split("\n/* ---- */\n")[0]

KEEP_SUBSETS = {"latin", "latin-ext", "thai"}
KEEP_WEIGHTS = {"400", "500", "600", "700"}

out = ["/* GoNai UI CSS for the sting. Generated by tools/make_ui_css.py from the app's compiled CSS\n"
       "   (GoNai main @5c30e78, next dev on the local JSON store). Do not hand-edit; re-run the tool. */\n"]
fonts = set()

# 1. font faces (each face is preceded by a /* subset */ comment; fallbacks have none)
for m in re.finditer(r"(?:/\*\s*([a-z-]+)\s*\*/\s*)?@font-face\s*\{([^}]*)\}", css):
    subset, body = m.group(1), m.group(2)
    fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
    if fam not in ("IBM Plex Sans Thai", "IBM Plex Mono", "IBM Plex Sans Thai Fallback", "IBM Plex Mono Fallback"):
        continue
    if not fam.endswith("Fallback"):
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        if subset not in KEEP_SUBSETS or weight not in KEEP_WEIGHTS:
            continue
        if fam == "IBM Plex Mono" and subset == "thai":
            continue
        f = re.search(r"url\(/_next/static/media/([^)]+)\)", body).group(1)
        fonts.add(f)
        body = body.replace("/_next/static/media/", "fonts/")
    out.append(("/* %s */\n" % subset if subset else "") + "@font-face {" + body + "}\n")

# 2. next/font variable classes
for m in re.finditer(r"\.__variable_[0-9a-f]+\s*\{[^}]*\}", css):
    out.append(m.group(0) + "\n")

# 3. compiled globals.css (everything after its webpack banner)
i = css.index("./app/globals.css ***!")
j = css.index("\n", css.index("\\****", i))
out.append(css[j + 1:])

open(dst, "w", encoding="utf-8").write("".join(out))
print("ui.css", sum(len(s) for s in out), "bytes ·", len(fonts), "font files:", " ".join(sorted(fonts)))
